format = """
[](#D32F54)\
$username\
[](bg:#28842F fg:#E34B6D)\
  ${custom.pwd}\
[](fg:#4BA251 bg:#dc844a)\
  $git_branch\
  $git_status\
[](fg:#E5A072 bg:#261B79)\
  $c\
  $elixir\
  $elm\
  $golang\
  $haskell\
  $java\
  $julia\
  $nodejs\
  $nim\
  $rust\
  $scala\
[](fg:#4C4299 bg:#9018b3)\
  $time\
[ ](fg:#A52DC7)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#D32F54"
style_root = "bg:#D32F54"
format = '[$user ]($style)'

[custom.pwd]
command = "set _pwd (pwd); if test $_pwd = '/home/enirq'; echo '~/'; else if pwd | grep -q 'enirq'; prompt_pwd; else; pwd; end;"
when = true
symbol = " @ "
style = "bg:#28842F"
format = "[$symbol($output) ]($style)"

[custom.mode]
command = "fish_mode_prompt"
when = true
style = "bg:#28842F"
format = "$output($style)"

[directory]
style = "bg:#28842F"
format = "${custom.pwd}"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
  style = "bg:#dc844a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#dc844a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#261B79"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#9018b3"
format = '[  $time ]($style)'
